model:
  vocab_size: 261  # bytes (0-255) + 5 special ones (but I will only use bytes + PAD)
  hidden_size: 768
  intermediate_size: 1152
  num_hidden_layers: 22
  num_attention_heads: 12
  hidden_activation: gelu
  pad_token_id: 256  # ONLY THIS ONE WILL BE USED
  mask_token_id: 257
  eos_token_id: 257
  bos_token_id: 258
  cls_token_id: 259
  sep_token_id: 260
  local_attention: 128
  max_position_embeddings: 768  # maximum size we will be able to process (architectural constraint for inference)

dataset:
  name: IIC/ClinText-SP
  split: train
  version: dedup
  dev: true

data:
  record_max_bytes: 4096  # how many raw bytes of a record are retained before crop sampling

tokenizer:
  type: baseline  # choose between baseline (one byte, one token), fixed chunk (chunks into a fixed size of bytes and creates a vector), or learned chunking
  batch_size: 1

loss:
  num_global_views: 2
  num_local_views: 4
  num_points: 17
  num_slices: 64
  ld: 0.1

aug:
  global_margin_min: 70  # the boundaries for global views (between min and max % of the original crop)
  global_margin_max: 100
  local_margin_min: 10  # the boundaries for local views (between min and max % of the original crop)
  local_margin_max: 35
  local_max_length: 128  # the max token to pad/truncate a local crop (tune every time you change max_position_embeddings)
  global_max_length: 512  # the max token to pad/truncate a local crop (this is indeed the max length we will see in training)

exp:
  device: cuda
  lr: 1e-4
  objective: mlm
  optim: adamw
  beta0: 0.9
  beta1: 0.95
  eps: 1e-8
  wd: 0.01
  epochs: 1000
  log_every_n_step: 1
  save_every_n_step: 500
  use_bf16: true

optim:
  warmup_steps: 0.05
  start_factor: 0.1
  end_factor: 1.0

mlm:
  max_length: 512
  mask_prob: 0.20
  replace_mask_prob: 0.8
  replace_random_prob: 0.1
